### ISSUE TITLE
PG syntax in doc

### ISSUE THREAD

**Issue by PredokMiF** [langpavel/node-pg-async#108]
Hi! In example you write:
`INSERT INTO bank_account (account, amount)
      VALUES ($1, $2)
      RETURNS id`
But in [PG syntax](https://www.postgresql.org/docs/9.5/static/sql-insert.html) yiu shoud use `RETURNING`

**Comment by langpavel** [comment]
Ohhh, you are right :+1:

**Comment by langpavel** [comment]
Fixed

**Comment by PredokMiF** [comment]
Thank you! )
