### ISSUE TITLE
Process not exiting

### ISSUE THREAD

**Issue by 131** [langpavel/node-pg-async#11]
I'm running a dummy 
```
"use strict";
require("babel-polyfill");
import PgAsync from 'pg-async';
// using connection string 
var pgAsync = new PgAsync("postgres://postgres@localhost/databas");
 
async function run(){
  var rows = await pgAsync.rows("SELECT * FROM files_list");
  console.log(rows);

  //pgAsync.closeConnections(); //nope
}

run();
```

With my .babelrc as
```
{
  "presets": ["es2015"],
  "plugins": ["syntax-async-functions","transform-regenerator"]
}
``` 

All is working fine but the nodejs process running after the final output.
I guess there is a need to "close" the sql link, i tried closeConnections/close/end with no success.
Can you help me here ?

**Comment by 131** [comment]
As documentation for pgAsync.getClient is await, i assume pgAsync.closeConnections() (that should use pgAsync.getClient under the hood) must also be "await style". I think the documentation is wrong here (no reference to the await requirement for closeConnections)
Switching my example to the following fixed everything :+1: 
```
await pgAsync.closeConnections(); 
```

**Comment by langpavel** [comment]
@131 Hi, thanks for feedback.

`pgAsync.closeConnections` is not async function: [index.js#L131](https://github.com/langpavel/node-pg-async/blob/master/src/index.js#L131). There is no need for awaiting.. 

Do you still experiencing this issue? Which version of `pg` do you use?

**Comment by 131** [comment]
It's sunday, with sun & wine & BBQ. Maybe a little too much wine. (no idea why my sample didn't work before, all is fine now)

**Comment by langpavel** [comment]
Ok, nice to hear :-)
