### ISSUE TITLE
pool, node-postgres and node-pg-async?

### ISSUE THREAD

**Issue by metainfa** [langpavel/node-pg-async#69]
Into v5.2.0 node-postgres replace internal pooling code with pg-pool [changelog v.5.2.0](https://github.com/brianc/node-postgres/commit/fd6a25a03027593fef5af23f1645791430300571), with v.6.0.0 add `new pg.Pool()` [changelog v.6.2.0](https://github.com/brianc/node-postgres/commit/1206f4d191eb0c8bff0737134eaadf9e4d740c09).  

My questions is:
1. `node-pg-async` uses Client connection with default pool through `pg.connect`  [getClient](https://github.com/langpavel/node-pg-async/blob/master/src/index.js#L75)?
2. will plan replace `pg.connect`(deprecated) to `new pg.Pool()` API?
3. if i want to use, for example [PgBouncer](https://github.com/pgbouncer/pgbouncer) as pool tool, will i can  disable `pg-pool` by set `pg.defaults.poolSize: 0`?

**Comment by bramkoot** [comment]
I'm happy to put some time in this if I could get some help on getting started @langpavel

**Comment by metainfa** [comment]
Hi! you may to try [dev branch](https://github.com/metainfa/node-pg-async/commits/dev). I've migrated to new api, but not tested much it.

Later i'll plan to add option to disable internal pool and use simple client `new pg.Client()`

**Comment by langpavel** [comment]
Hi @metainfa.

I send you invitation for this project. Feel free to create and push into new branch `develop` and/or you can create PR

**Comment by metainfa** [comment]
Hi @langpavel. I've pushed to `develop` branch.

**Comment by myfreeweb** [comment]
I'm seeing the `pg.connect` deprecation warning in my app already…

**Comment by metainfa** [comment]
@myfreeweb what version are you using? Into [npm](https://www.npmjs.com/) repo is old version `2.4.3`. Are you try from github `3.0.0`?

**Comment by metainfa** [comment]
@myfreeweb I update `pg` to version `6.4` you can try [from my repo](https://github.com/metainfa/node-pg-async/tree/pg-6.4) if all ok, then it can be merged.

**Comment by langpavel** [comment]
@metainfa @myfreeweb Hi, thanks for effort.
If it will be ok, I can publish new package.
@metainfa Do you have access to npm? or it is stil only mine? :smile:

**Comment by metainfa** [comment]
Hi Pavel! 

No I don't have access to npm. 

I update `eslint-plugin-import` to  `2.7.0`, now at my local machine tests passed for next `lts` node.js:
- node v4.8.3
- node v6.11.0
- node v8.1.3

**Comment by uLan08** [comment]
Any updates on a publish? Seeing the pg.connect depreciation message on `pg-async 2.4.3`

**Comment by langpavel** [comment]
@metainfa have you account on NPM? I will give you permission.

**Comment by metainfa** [comment]
https://www.npmjs.com/~metainfa

@langpavel What about [PR?](https://github.com/langpavel/node-pg-async/pull/101)

**Comment by langpavel** [comment]
@metainfa Please review `pg-async@3.1.0` is on NPM

**Comment by metainfa** [comment]
@langpavel  I switched to branch `prepare-3.1`, when i pushed last commit and all test passed (exclude dependencies). At my platform (LInux amd64) all ok. Today i switched to package from npm - also i not have any issue.

**Comment by langpavel** [comment]
Great @metainfa, It's on NPM, so I cannot do anything more except publish more recent version :-)

**Comment by uLan08** [comment]
@langpavel @metainfa 
This might be related, I posted an issue #104
