### ISSUE TITLE
Should PgAsync async instance live the entire duration or be created per use?

### ISSUE THREAD

**Issue by ryancole** [langpavel/node-pg-async#71]
Sorry for the question-as-an-issue. I'm unsure of the appropriate scope for `PgAsync` instance, though. It sounds like it uses connection pooling, but does this mean I'm free to create an instance of this whenever needed and it'll pick up a connection from a pool, or does this mean I should have a single instance of `PgAsync` used throughout the entire application lifetime?

Thanks!

**Comment by bramkoot** [comment]
You should create a single instance, ideally once in your application. For every query that you do, a connection is retrieved from the pool and returned automatically. Creating new instances would mean you set up new pools for every use, which is not what you want.

**Comment by ryancole** [comment]
Thanks a lot, @bramkoot !
